#!/bin/bash
# ============================================================
# SatelliteEval - Local Deployment Component
# ============================================================
# Description:
#   In a single-device setup, this component reads the command file
#   generated by the Planning Component and executes it directly.
#   No satellite communication or encoding is performed.
#
# Usage:
#   bash deploy_local.sh --input <command_file> [--dry-run] [--verbose]
# ============================================================

set -euo pipefail

# Initialize variables
INPUT_FILE=""
DRY_RUN=false
VERBOSE=false

# ----------------------------
# Argument parsing
# ----------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
        --input)
            INPUT_FILE="$2"
            shift 2
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --verbose)
            VERBOSE=true
            shift
            ;;
        *)
            echo "[ERROR] Unknown option: $1"
            echo "Usage: $0 --input <path> [--dry-run] [--verbose]"
            exit 1
            ;;
    esac
done

# ----------------------------
# Argument validation
# ----------------------------
if [[ -z "$INPUT_FILE" ]]; then
    echo "[ERROR] Missing required argument: --input <path>"
    exit 1
fi

if [[ ! -f "$INPUT_FILE" ]]; then
    echo "[ERROR] Command file not found: $INPUT_FILE"
    exit 1
fi

# ----------------------------
# Read command
# ----------------------------
cmd=$(cat "$INPUT_FILE")

echo "[INFO] Reading command from: $INPUT_FILE"
echo "[CMD]  $cmd"
echo

if [[ "$DRY_RUN" == true ]]; then
    echo "[INFO] Dry run mode: command not executed."
    exit 0
fi

# ----------------------------
# Execute command
# ----------------------------
if [[ "$VERBOSE" == true ]]; then
    echo "[INFO] Executing command (verbose mode)..."
    eval "$cmd"
else
    eval "$cmd" >/dev/null 2>&1
fi

# ----------------------------
# Check execution status
# ----------------------------
status=$?
if [[ $status -eq 0 ]]; then
    echo "[OK] Command executed successfully."
else
    echo "[ERROR] Command execution failed with status $status."
fi
